apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - name: frontend
          image: h4mdi/front-end:latest
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: prod-cluster
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s_f
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 4200
      targetPort: 80
  selector:
    io.kompose.service: frontend

