apiVersion: v1
kind: Pod
metadata:
  namespace: prod-cluster
  annotations:
    kompose.cmd: kompose convert -f docker-compose-global.yml --out k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: config
  name: config
spec:
  containers:
    - env:
        - name: CONFIG_KEYSTORE_PASSWORD
          value: secure-keystore-password
        - name: CONFIG_KEY_PASSWORD
          value: secure-keystore-password
        - name: CONFIG_SERVICE_PASSWORD
          value: cfg-password
        - name: CONFIG_SERVICE_USER
          value: user
        - name: EUREKA_USER
          value: user
        - name: POSTGRES_USER
          value: dbuser
        - name: SPRING_PROFILES_ACTIVE
          value: docker,native
      image: h4mdi/config
      name: config
      ports:
        - containerPort: 8888
      resources: {}
  restartPolicy: OnFailure
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-global.yml --out k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: config
  name: config
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: config
status:
  loadBalancer: {}
