apiVersion: v1
kind: Pod
metadata:
  namespace: prod-cluster
  annotations:
    kompose.cmd: kompose convert -f docker-compose-global.yml --out k8s
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.network/docker-eshopnet: "true"
    io.kompose.service: catalog
  name: catalog
spec:
  containers:
    - name: catalog
      image: h4mdi/catalog
      env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: CONFIG_SERVICE_PASSWORD
        - name: CONFIG_SERVICE_USER
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: CONFIG_SERVICE_USER
        - name: EUREKA_USER
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: EUREKA_USER
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: POSTGRES_USER
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: SPRING_PROFILES_ACTIVE

      resources: {}
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: catalog
