apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: CONFIG_SERVICE_USER
              value: "cfguser"
            - name: CONFIG_SERVICE_PASSWORD
              value: "cfgpassword"
            - name: EUREKA_USER
              value: "user"
          image: h4mdi/gateway:latest
          name: api-gateway
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always

status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: gateway
status:
  loadBalancer: {}