apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-command
  template:
    metadata:
      labels:
        app: catalog-command
    spec:
      containers:
        - name: catalog-command
          image: h4mdi/catalog-command:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: CONFIG_SERVICE_USER
              value: "cfguser"
            - name: CONFIG_SERVICE_PASSWORD
              value: "cfgpassword"
            - name: EUREKA_USER
              value: "user"
            - name: MONGO_USER
              value: "user"
            - name: MONGO_PASSWORD
              value: "pass"
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-command
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: catalog-command