apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  strategy: {}
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker,native
            - name: CONFIG_SERVICE_USER
              value: cfguser
            - name: CONFIG_SERVICE_PASSWORD
              value: cfgpassword
            - name: CONFIG_KEY_PASSWORD
              value: secure-keystore-password
            - name: EUREKA_USER
              value: user
            - name: POSTGRES_USER
              value: dbuser
          image: h4mdi/config-server:latest
          name: config
          ports:
            - containerPort: 8888
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: config
  name: config
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    app: config