apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  strategy: {}
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: CONFIG_SERVICE_USER
              value: "cfguser"
            - name: CONFIG_SERVICE_PASSWORD
              value: "cfgpassword"
            - name: EUREKA_USER
              value: "user"
          image: h4mdi/discovery:latest
          name: discovery-server
          ports:
            - containerPort: 8761
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discovery-server
  name: discovery-server
spec:
  type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 31001
  selector:
    app: discovery-server
status:
  loadBalancer: {}