apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: h4mdi/pg-shop
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_PASSWORD
              value: dbpass
            - name: POSTGRES_USER
              value: dbuser
            - name: PGTZ
              value: Europe/Amsterdam
            - name: CATALOG_DB_USER
              value: catalogdbuser
            - name: CATALOG_DB_PASSWORD
              value: dbpass
            - name: CATALOG_DB_NAME
              value: catalogdb
            - name: RATING_DB_USER
              value: ratingdbuser
            - name: RATING_DB_NAME
              value: ratingdb
            - name: RATING_DB_PASSWORD
              value: dbpass
            - name: ORDER_DB_USER
              value: orderdbuser
            - name: ORDER_DB_PASSWORD
              value: dbpass
            - name: ORDER_DB_NAME
              value: orderdb
              
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "-U"
                - "dbuser"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - "pg_isready"
                - "-U"
                - "dbuser"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources: {}
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres-order-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-order-claim0
          persistentVolumeClaim:
            claimName: postgres-order-claim0
    
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-order-claim0
  name: postgres-order-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}